apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pt-hpa
  namespace: pt-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pt-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
